In [1]:
import pandas as pd

df = pd.read_csv('merge.csv')
df.month = df.month.astype('str')

In [2]:
(df.month == '8').sum()

247

In [3]:
df_dum = pd.get_dummies(df, prefix=['month'])

In [4]:
df_dum

,tavg,tmin,tmax,wt,pH,DO,NTU,chl-a,cyan,month_1,...,month_11,month_12,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9
0,8.8,0.6,16.9,7.3,8.9,12.0,3.2,52.4,0.0,0,...,0,0,0,1,0,0,0,0,0,0
1,8.9,1.1,15.6,7.8,8.9,11.0,3.5,47.6,0.0,0,...,0,0,0,1,0,0,0,0,0,0
2,17.7,11.6,25.5,13.4,8.8,9.3,3.8,24.0,0.0,0,...,0,0,0,0,1,0,0,0,0,0
3,15.5,7.2,22.5,14.9,8.4,8.5,4.9,21.8,0.0,0,...,0,0,0,0,0,1,0,0,0,0
4,19.5,12.2,27.3,16.1,8.0,8.4,4.8,16.1,0.0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2290,14.3,7.0,21.0,18.4,7.3,6.9,5.2,3.9,40.0,0,...,1,0,0,0,0,0,0,0,0,0
2291,11.0,5.4,17.9,16.3,7.4,7.3,9.5,5.8,100.0,0,...,1,0,0,0,0,0,0,0,0,0
2292,9.5,2.6,16.0,15.1,7.4,8.2,5.3,7.8,110.0,0,...,1,0,0,0,0,0,0,0,0,0
2293,9.5,2.4,17.8,13.0,7.5,7.3,8.3,4.6,0.0,0,...,1,0,0,0,0,0,0,0,0,0
2294,8.9,2.7,15.3,10.9,7.7,9.0,3.3,2.6,0.0,0,...,0,1,0,0,0,0,0,0,0,0

In [5]:
import numpy as np

skewed_data = ['pH','NTU','chl-a','cyan']

df_dum[skewed_data] = df_dum[skewed_data].applymap(lambda x: np.log(x) if x > 0 else 0)

In [6]:
from sklearn.model_selection import train_test_split

target = 'cyan'
features = df_dum.columns.drop(target)

train, test = train_test_split(df_dum,test_size=0.2,random_state=2)

In [7]:
X_train = train[features]
y_train = train[target]
X_test = test[features]
y_test = test[target]

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

model = LinearRegression()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)

print('테스트 데이터 MSE :',round(mean_squared_error(y_test,y_pred)))
print('테스트 데이터 RMSE :',round(mean_squared_error(y_test,y_pred)**0.5))
print('테스트 데이터 MAE :',round(mean_absolute_error(y_test,y_pred)))
print('테스트 데이터 r2_score :',r2_score(y_test,y_pred))

테스트 데이터 MSE : 6
테스트 데이터 RMSE : 2
테스트 데이터 MAE : 2
테스트 데이터 r2_score : 0.483783534242746

In [84]:
df_dum

,tavg,tmin,tmax,wt,pH,DO,NTU,chl-a,cyan,month_1,...,month_11,month_12,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9
0,8.8,0.6,16.9,7.3,2.186051,12.0,1.163151,3.958907,0.000000,0,...,0,0,0,1,0,0,0,0,0,0
1,8.9,1.1,15.6,7.8,2.186051,11.0,1.252763,3.862833,0.000000,0,...,0,0,0,1,0,0,0,0,0,0
2,17.7,11.6,25.5,13.4,2.174752,9.3,1.335001,3.178054,0.000000,0,...,0,0,0,0,1,0,0,0,0,0
3,15.5,7.2,22.5,14.9,2.128232,8.5,1.589235,3.081910,0.000000,0,...,0,0,0,0,0,1,0,0,0,0
4,19.5,12.2,27.3,16.1,2.079442,8.4,1.568616,2.778819,0.000000,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2290,14.3,7.0,21.0,18.4,1.987874,6.9,1.648659,1.360977,3.688879,0,...,1,0,0,0,0,0,0,0,0,0
2291,11.0,5.4,17.9,16.3,2.001480,7.3,2.251292,1.757858,4.605170,0,...,1,0,0,0,0,0,0,0,0,0
2292,9.5,2.6,16.0,15.1,2.001480,8.2,1.667707,2.054124,4.700480,0,...,1,0,0,0,0,0,0,0,0,0
2293,9.5,2.4,17.8,13.0,2.014903,7.3,2.116256,1.526056,0.000000,0,...,1,0,0,0,0,0,0,0,0,0
2294,8.9,2.7,15.3,10.9,2.041220,9.0,1.193922,0.955511,0.000000,0,...,0,1,0,0,0,0,0,0,0,0

In [27]:
tavg = 28.5
tmin = 24.5
tmax = 32
wt = 30.1
pH = 9.2
DO = 10.1
NTU = 7.8
chl_a = 53.1

X_pred = [[tavg,tmin,tmax,wt,np.log(pH),DO,np.log(NTU),np.log(chl_a),0,0,0,0,0,0,0,1,0,0,0,0]]


# X_pred = [[7,7,7,7,np.log(7),7,np.log(7),np.log(7),0,0,0,0,0,0,1,0,0,0,0,0]]

# df_dum[skewed_data] = df_dum[skewed_data].applymap(lambda x: np.log(x) if x > 0 else 0)

y_pred = model.predict(X_pred)

if y_pred < 0:
    predict = 0
else:
    predict = int(np.e**y_pred)


print(predict)

505

In [42]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_jobs=-1, random_state=2)

rf.fit(X_train,y_train)
y_pred_rf = rf.predict(X_test)

print('훈련 R2:',r2_score(y_train,rf.predict(X_train)))
print('테스트 데이터 MSE :',mean_squared_error(y_test,y_pred_rf))
print('테스트 데이터 RMSE :',mean_squared_error(y_test,y_pred_rf)**0.5)
print('테스트 데이터 MAE :',mean_absolute_error(y_test,y_pred_rf))
print('테스트 데이터 r2_score :',r2_score(y_test,y_pred_rf))

print('훈련 MSE:',mean_squared_error(y_train, rf.predict(X_train)))
print('테스트 MSE:',mean_squared_error(y_test, rf.predict(X_test)))
print('훈련 R2:',r2_score(y_train,rf.predict(X_train)))
print('테스트 R2:',r2_score(y_test,rf.predict(X_test)))

훈련 R2: 0.940837818282966
테스트 데이터 MSE : 4.2924535351738555
테스트 데이터 RMSE : 2.071823722031837
테스트 데이터 MAE : 1.5059267665656302
테스트 데이터 r2_score : 0.6041201222967969
훈련 MSE: 0.5896678192568009
테스트 MSE: 4.292453535173856
훈련 R2: 0.940837818282966
테스트 R2: 0.6041201222967969

In [44]:
X_train

,tavg,tmin,tmax,wt,pH,DO,NTU,chl-a,month_1,month_10,month_11,month_12,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9
1079,10.7,6.7,15.5,13.1,2.054124,10.6,1.163151,2.128232,0,0,0,0,0,1,0,0,0,0,0,0
695,9.8,-1.0,20.1,13.8,2.104134,10.8,0.182322,1.029619,0,0,0,0,0,0,1,0,0,0,0,0
1415,7.6,0.6,17.2,13.0,1.916923,6.7,1.308333,1.629241,0,0,1,0,0,0,0,0,0,0,0,0
1484,9.3,-0.4,19.1,6.4,1.987874,12.6,1.335001,1.504077,0,0,0,0,0,1,0,0,0,0,0,0
730,-2.6,-5.4,-0.1,7.9,2.066863,10.5,0.641854,1.808289,0,0,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1071,4.4,1.4,9.0,6.2,2.079442,12.2,-0.223144,2.493205,0,0,0,0,1,0,0,0,0,0,0,0
433,2.1,-3.4,10.4,6.5,2.128232,14.2,1.667707,3.478158,0,0,0,0,1,0,0,0,0,0,0,0
674,13.4,8.6,18.3,15.5,2.028148,9.2,2.509599,1.386294,0,0,1,0,0,0,0,0,0,0,0,0
1099,30.4,26.1,35.7,25.0,2.001480,7.4,0.993252,1.902108,0,0,0,0,0,0,0,0,0,0,1,0
1608,2.8,-2.4,4.6,6.4,2.014903,7.7,0.875469,1.902108,1,0,0,0,0,0,0,0,0,0,0,0

In [43]:
y_pred = rf.predict(X_pred)

if y_pred < 0:
    predict = 0
else:
    predict = int(np.e**y_pred)


print(predict)

13174

In [46]:
import pickle
model = None

with open('model.pkl','rb') as pickle_file:
    model = pickle.load(pickle_file)

y_pred = model.predict(X_pred)

if y_pred < 0:
    predict = 0
else:
    predict = int(np.e**y_pred)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 1.0.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator RandomForestRegressor from version 1.0.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(

In [47]:
predict

20405

In [41]:
params = {'n_estimators' : [100,300,500],
         'max_depth' : [3,5,7],
         'max_features' : [8,10,13,16,18],
         }

rf2 = RandomForestRegressor(n_jobs=-1, random_state=2)

clf2 = GridSearchCV(rf2, params)

clf2.fit(X_train,y_train)

print('훈련 MSE:',mean_squared_error(y_train, clf2.predict(X_train)))
print('테스트 MSE:',mean_squared_error(y_test, clf2.predict(X_test)))
print('훈련 R2:',r2_score(y_train,clf2.predict(X_train)))
print('테스트 R2:',r2_score(y_test,clf2.predict(X_test)))

훈련 MSE: 2.711425425914504
테스트 MSE: 4.653842638141112
훈련 R2: 0.7279589651639444
테스트 R2: 0.5707903092391575

In [34]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV

params = {'n_estimators' : randint(low=100, high=500),
          'max_depth' : randint(low=3, high=7),
          'max_features' : randint(low=1, high=10),
          'min_samples_leaf' : randint(low=1, high=15)
         }

rf = RandomForestRegressor(n_jobs=-1, random_state=2)

clf = RandomizedSearchCV(rf, params, random_state=2, cv=10)

clf.fit(X_train,y_train)
print('훈련 MSE:',mean_squared_error(y_train, clf.predict(X_train)))
print('테스트 MSE:',mean_squared_error(y_test, clf.predict(X_test)))
print('훈련 R2:',r2_score(y_train,clf.predict(X_train)))
print('테스트 R2:',r2_score(y_test,clf.predict(X_test)))

훈련 MSE: 3.7350228635032705
테스트 MSE: 5.123018726386825
훈련 R2: 0.6252600292036222
테스트 R2: 0.5275196317783573

In [38]:
lgbm = LGBMRegressor(random_state=2, max_depth = 3)
lgbm.fit(X_train,y_train)

print('훈련 MSE:',mean_squared_error(y_train, lgbm.predict(X_train)))
print('테스트 MSE:',mean_squared_error(y_test, lgbm.predict(X_test)))
print('훈련 R2:',r2_score(y_train,lgbm.predict(X_train)))
print('테스트 R2:',r2_score(y_test,lgbm.predict(X_test)))

훈련 MSE: 3.372915348476557
테스트 MSE: 4.820169103057464
훈련 R2: 0.6615907732352619
테스트 R2: 0.5554505274452879

In [39]:
xgb = XGBRegressor(random_state=2, max_depth = 3)
xgb.fit(X_train,y_train)

print('훈련 MSE:',mean_squared_error(y_train, xgb.predict(X_train)))
print('테스트 MSE:',mean_squared_error(y_test, xgb.predict(X_test)))
print('훈련 R2:',r2_score(y_train,xgb.predict(X_train)))
print('테스트 R2:',r2_score(y_test,xgb.predict(X_test)))

훈련 MSE: 2.0374188233809
테스트 MSE: 4.401323154660435
훈련 R2: 0.7955829727752668
테스트 R2: 0.5940794098476647

In [40]:
gb = GradientBoostingRegressor(random_state=2, max_depth = 3)
gb.fit(X_train,y_train)

print('훈련 MSE:',mean_squared_error(y_train, gb.predict(X_train)))
print('테스트 MSE:',mean_squared_error(y_test, gb.predict(X_test)))
print('훈련 R2:',r2_score(y_train,gb.predict(X_train)))
print('테스트 R2:',r2_score(y_test,gb.predict(X_test)))

훈련 MSE: 3.1724001493341603
테스트 MSE: 4.769283650416502
훈련 R2: 0.6817087384035858
테스트 R2: 0.5601435373062695